<a href="https://colab.research.google.com/github/KVijay2/DeepLearning-PyTorch/blob/main/deepLearningTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
import torch
import numpy as np

In [ ]:
np1 = np.random.randint(0,10, size=(5, 5))
np1

array([[6, 0, 8, 1, 0],
       [5, 3, 6, 6, 3],
       [8, 0, 8, 4, 4],
       [7, 8, 0, 1, 8],
       [4, 6, 5, 8, 6]])

In [ ]:
tensor1 = torch.tensor(np1)
tensor1

tensor([[6, 0, 8, 1, 0],
        [5, 3, 6, 6, 3],
        [8, 0, 8, 4, 4],
        [7, 8, 0, 1, 8],
        [4, 6, 5, 8, 6]])

In [ ]:
tensor2 = torch.arange(10)
tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor2.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensorA=torch.tensor([1,2,3,4])
tensorB=torch.tensor([5,6,7,8])

In [ ]:
tensorC = tensorA + tensorB

In [ ]:
torch.add(tensorC,tensorA)

tensor([ 7, 10, 13, 16])